### ISSUE TITLE
[TODO]: 코드 리팩토링 및 개선 작업

### ISSUE THREAD

**Issue by hongii** [hongii/Book-Shop#15]
## 중복 코드 모듈화
- [x] 비밀번호 암호화 하는 로직을 따로 유틸함수로 모듈화
- [x] access token과 refresh token 발급하는 로직을 따로 유틸함수로 모듈화

## 코드 분리
- [ ] Service와 Model의 역할 분리
- [x] authMiddleware.js 파일에 있는 두개의 Token관련 미들웨어 코드를 분리
  - access token과  refresh token 유효성 검증하고 sql쿼리문 수행하는 코드 분리 해보기
