### ISSUE TITLE
[TODO] 코드 리뷰를 통해 피드백 받은 부분 개선

### ISSUE THREAD

**Issue by hongii** [hongii/Book-Shop#18]
## 리팩토링 TODO LIST
- [ ] TS로 마이그레이션
- [ ] 서브쿼리의 실행 계획을 EXPLAIN 키워드를 사용하여 확인해보기
  - 성능면에서 어떤 쿼리를 구상하는 것이 좋을지 고민해볼 필요 있음
- [ ] booksSevice.js에서 쿼리 결과값으로 받아온 results에 대한 중복코드 제거해보기(도서조회 api와 개별 도서 조회 api)
- [ ] 에러 핸들러 미들웨어에서 커스텀 에러 클래스 수정 ⇒ 커스텀 에러가 Status code를 직접 판단해서 에러 핸들러 미들웨어로 던져주는게 아니라 에러 핸들러 미들웨어에서 판단하도록 해야함
- [ ] 주문하기 api에서 요청받을때 req에 담겨진 모든 데이터를 db에 저장되어 있는 값과 일치하는지 확인하는 과정에서, 쿼리 수행 결과인 results의 길이로만 판단하는건 어떨까? ⇒ 고민해보기
- [ ] 장바구니 제거 api의 url 수정하기
  - 만약, DELETE: carts/1 로 API를 호출하면 1은 id 인데, 그럼 1이라는 id는 어떤 id인가? → 보통 cart id일 것으로 추측할 것이다. 
  - 따라서, 이렇게 짜여진 url의 파라미터에는 bookId가 아닌 cartId가 들어가는 것이 더 적절하다. 
  - 만약, url의 파라미터가 bookId임을 표현하고 싶다면, book의 id임을 확실하게 알 수 있도록 리소스를 제대로 지정해주는 것이 좋다.
- [ ] asyncWrapper 미들웨어로 try-catch부분을 분리하여 따로 만들어 두었으니 트랜잭션 부분도 한번 만들어보기
  - 주문하기 api의 트랜잭션 부분에서 현재 코드에서도 트랜잭션 보장은 된다.
- [ ] authMiddleware에서 Service 부분은 따로 분리하고 호출해서 사용하도록 수정
- [ ] Model 분리해보기
