### ISSUE TITLE
[TODO]: access token을 이용하여 사용자 검증하기

### ISSUE THREAD

**Issue by hongii** [hongii/Book-Shop#2]
## JWT 유효성 검증이 필요한 기능
- 좋아요 API
    - [x] 좋아요 추가
    - [x] 좋아요 삭제
- 장바구니 API
    - [x] 장바구니에 물품 담기
    - [x] 장바구니 목록 조회
    - [x] 장바구니에서 물품 제거
- 결제(주문)  API
    - [x] 결제 요청
    - [x] 전체 주문 내역 조회
    - [x] 주문 내역의 상세 상품 조회
<br/>

## 유효성 검증 구현 과정 설명
1. 위의 API 엔드포인트에서,  request의 body를 통해 user_id를 받아오는 코드를 삭제
2. 각 API 엔드포인트에서 헤더의 Authorization 필드에 있는 JWT 토큰을 추출 
    → (단, 프론트에서 request header의 Authorization에 access token을 넣어주는 로직을 구현하기 전까지는 cookie-parser모듈을 사용하여 request의 cookie에서 access token을 받아올 예정)
3. 추출한 토큰을 jsonwebtoken의 verify() 메서드로 유효성을 검증
4. 토큰이 유효한 경우, 해당 요청에 대한 사용자의 정보를 활용하여 사용자 요청을 수행하여 응답을 반환
5. 토큰이 유효하지 않은 경우, 적절한 에러 응답을 반환
<br/>

## 유효성 검증 과정에서 추가로 구현할 로직
- refresh token의 도입 : access token의 유효기간을 짧게 설정하고, 만료된 access token은 refresh token으로 재발급 해주는 로직
